version: '3'

services:
  backend-end:
      build:
        context: ./backend
        dockerfile: ./Dockerfile
      restart: always
      ports:
        - "8080:8080"
      deploy:
        mode: replicated
        replicas: 1

  front-end:
      build:
        context: ./frontend
        dockerfile: ./Dockerfile
      restart: always
      ports:
        - "4173:4173"
      deploy:
        mode: replicated
        replicas: 1